#配置端口
server:
  port: 8888

#应用名称
Spring:
  application:
    name: admin-version

  #配置数据源
  datasource:
    dynamic:
      primary: first
      datasource:
        first:
          username: root
          password: Yxtl1234..
          url: jdbc:mysql://39.101.193.57:3306/yxtl_db_admin?useUnicode=yes&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        second:
          username: root
          password: Yxtl1234..
          url: jdbc:mysql://39.101.193.57:3306/yxtl_db_lora?useUnicode=yes&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource

          #   数据源其他配置
          initialSize: 5
          minIdle: 5
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true

  #配置文件上传最大文件
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  #配置redis
  redis:
    jedis:
      pool:
        #最大连接数, 不超过Redis实例的最大连接数(redis默认10000)
        max-active: 18
        max-wait: 100000
        max-idle: 8
        min-idle: 1
    timeout: 6000
    host: 39.101.193.57
    port: 6379
    password: yxtl1234..--

#整合mybatis-plus
mybatis-plus:
  mapper-locations: classpath:**/*Mapper.xml